controller:
  publishService:
    enabled: true
  service:
    enabled: true
  metrics:
    enabled: true
    service:
      annotations: {}
      prometheus.io/scrape: "true"
      prometheus.io/port: "10254"
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus
      namespace: "default"
      honorLabels: true
    prometheusRule:
      enabled: true
      namespace: "default"
      rules:
        - alert: TooMany500s
          expr: 100 * ( sum( nginx_ingress_controller_requests{status=~"5.+"} ) / sum(nginx_ingress_controller_requests) ) > 5
          for: 1m
          labels:
            severity: critical
          annotations:
            description: Too many 5XXs
            summary: More than 5% of the all requests did return 5XX, this require your attention
