controller:
  publishService:
    enabled: true
  service:
    enabled: true
    type: ClusterIP
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus
